export const calculators = [
  {
    to: '/kalkulacky/prijem-v-czk',
    icon: 'crowns',
    short: 'Koruny',
    title: 'Příjem v korunách',
    description: 'Odhalte, co s vaším příjmem udělala inflace a jak se změnila jeho reálná kupní síla.',
    accent: 'copper',
  },
  {
    to: '/kalkulacky/prijem-v-menach',
    icon: 'currencies',
    short: 'Měny',
    title: 'Příjem v EUR a USD',
    description: 'Přepočítejte příjem podle průměrných ročních kurzů eura a amerického dolaru.',
    accent: 'blue',
  },
  {
    to: '/kalkulacky/prijem-v-bitcoinu',
    icon: 'bitcoin',
    short: 'Bitcoin',
    title: 'Příjem v bitcoinu',
    description: 'Zjistěte, kolik bitcoinů představoval váš příjem na konci každého roku.',
    accent: 'orange',
  },
  {
    to: '/kalkulacky/prijem-v-sp500',
    icon: 'chart',
    short: 'S&P 500',
    title: 'Příjem v S&P 500',
    description: 'Porovnejte příjem s počtem podílů indexového fondu SPDR S&P 500 (SPY).',
    accent: 'green',
  },
  {
    to: '/kalkulacky/prijem-ve-zlate',
    icon: 'gold',
    short: 'Zlato',
    title: 'Příjem ve zlatě',
    description: 'Podívejte se, kolik gramů zlata jste si mohli za roční příjem koupit.',
    accent: 'gold',
  },
  {
    to: '/kalkulacky/prijem-v-nemovitostech',
    icon: 'building',
    short: 'Nemovitosti',
    title: 'Příjem v nemovitostech',
    description: 'Převeďte příjem na metry čtvereční podle kraje, velikosti obce a typu nemovitosti.',
    accent: 'violet',
  },
  {
    to: '/kalkulacky/realna-inflace',
    icon: 'percent',
    short: 'Reálná inflace',
    title: 'Reálná inflace',
    description: 'Poskládejte si vlastní inflaci z bitcoinu, zlata, S&P 500 a nemovitostí podle vlastních vah.',
    accent: 'red',
    alwaysReady: true,
  },
]
